# Generated by Django 4.0.3 on 2022-08-04 17:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('knihy', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='kniha',
            options={'verbose_name_plural': 'Knihy'},
        ),
        migrations.AddField(
            model_name='kniha',
            name='autor',
            field=models.CharField(default='', max_length=200),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='kniha',
            name='rok',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
    ]
